# Project: Langage_C_Project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = AuversackHoudart_private.res
OBJ      = Functions/AuversackHoudart_affichage.o Functions/AuversackHoudart_ajout.o Functions/AuversackHoudart_compter.o Functions/AuversackHoudart_operation.o Functions/AuversackHoudart_outils.o Functions/AuversackHoudart_recuperation.o Functions/AuversackHoudart_suppression.o AuversackHoudart_Main.o $(RES)
LINKOBJ  = Functions/AuversackHoudart_affichage.o Functions/AuversackHoudart_ajout.o Functions/AuversackHoudart_compter.o Functions/AuversackHoudart_operation.o Functions/AuversackHoudart_outils.o Functions/AuversackHoudart_recuperation.o Functions/AuversackHoudart_suppression.o AuversackHoudart_Main.o $(RES)
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AuversackHoudart.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Functions/AuversackHoudart_affichage.o: Functions/AuversackHoudart_affichage.c
	$(CC) -c Functions/AuversackHoudart_affichage.c -o Functions/AuversackHoudart_affichage.o $(CFLAGS)

Functions/AuversackHoudart_ajout.o: Functions/AuversackHoudart_ajout.c
	$(CC) -c Functions/AuversackHoudart_ajout.c -o Functions/AuversackHoudart_ajout.o $(CFLAGS)

Functions/AuversackHoudart_compter.o: Functions/AuversackHoudart_compter.c
	$(CC) -c Functions/AuversackHoudart_compter.c -o Functions/AuversackHoudart_compter.o $(CFLAGS)

Functions/AuversackHoudart_operation.o: Functions/AuversackHoudart_operation.c
	$(CC) -c Functions/AuversackHoudart_operation.c -o Functions/AuversackHoudart_operation.o $(CFLAGS)

Functions/AuversackHoudart_outils.o: Functions/AuversackHoudart_outils.c
	$(CC) -c Functions/AuversackHoudart_outils.c -o Functions/AuversackHoudart_outils.o $(CFLAGS)

Functions/AuversackHoudart_recuperation.o: Functions/AuversackHoudart_recuperation.c
	$(CC) -c Functions/AuversackHoudart_recuperation.c -o Functions/AuversackHoudart_recuperation.o $(CFLAGS)

Functions/AuversackHoudart_suppression.o: Functions/AuversackHoudart_suppression.c
	$(CC) -c Functions/AuversackHoudart_suppression.c -o Functions/AuversackHoudart_suppression.o $(CFLAGS)

AuversackHoudart_Main.o: AuversackHoudart_Main.c
	$(CC) -c AuversackHoudart_Main.c -o AuversackHoudart_Main.o $(CFLAGS)

AuversackHoudart_private.res: AuversackHoudart_private.rc AuversackHoudart_ressources.rc
	$(WINDRES) -i AuversackHoudart_private.rc --input-format=rc -o AuversackHoudart_private.res -O coff 

